PIM-9499: Fix warning display when a job is running with warnings
akeneo/pim-community-dev pull request #13072
Opened 2020-10-22 08:24 UTC by anaisbaunelemaire

**Description (for Contributor and Core Developer)**

When a job was running, like a product import, when there were warnings displayed, it was impossible to read them as every time we clicked on "display item", the item displayed immediately closed back.

Confirm by PM: "when a user expands a warning, it has to stay expanded until he decides to collapse."

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2020-10-23 13:04 UTC, juliensnz commented on src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/summary-table.js
> +                }
What do you think about this solution:

```suggestion
                const stepIndex = parseInt(event.currentTarget.dataset.stepIndex);
                const warningIndex = parseInt(event.currentTarget.dataset.warningIndex);
                
                this.expandedWarnings[stepIndex] = this.expandedWarnings[stepIndex] || [];
                
                this.expandedWarnings[stepIndex] = this.expandedWarnings[stepIndex].includes(warningIndex) ?
                    this.expandedWarnings[stepIndex].filter(index => index === warningIndex) :
                    [...this.expandedWarnings[stepIndex], warningIndex];
```

2020-10-23 14:19 UTC, anaisbaunelemaire commented on src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/summary-table.js
> +                }
Many Thanks for your feedback, Julien !
Your proposal seemed good to me but I tested and the "hide item" doesn't work during the execution of the job.
Another problem: once the execution of the job is finished, when I have 2 open warnings and I want to close one, the other closes. I'll work on your piece of code, to find out where the error is.

2020-11-05 09:17 UTC, anaisbaunelemaire commented on src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/summary-table.js
> +        ? this.expandedWarnings[stepIndex].filter(index => index !== warningIndex)
@juliensnz the mistake was there:
`index !== warningIndex` (et non `index === warningIndex`) 
It works, now ! Thx for your improvement proposal :-)

2020-11-05 09:21 UTC, jmleroux requested changes
The CHANGELOG should not remoive entries

2020-11-05 09:21 UTC, jmleroux commented on CHANGELOG.md
> -- BH-138: clear Locale cache on save
???

2020-11-05 09:25 UTC, nmarniesse approved these changes

2020-11-05 09:25 UTC, nmarniesse commented on CHANGELOG.md
> -- BH-138: clear Locale cache on save
Why removing this line and the two others below?

2020-11-05 09:29 UTC, anaisbaunelemaire commented on CHANGELOG.md
> -- BH-138: clear Locale cache on save
I don't understand !? I resolved the conflicts on the changelog file accepting master and local changes.
Well, I'll revert that...!

2020-11-05 09:34 UTC, anaisbaunelemaire commented on CHANGELOG.md
> -- BH-138: clear Locale cache on save
Solved @jmleroux

2020-11-05 09:34 UTC, anaisbaunelemaire commented on CHANGELOG.md
> -- BH-138: clear Locale cache on save
Solved @nmarniesse ;-)

2020-11-05 10:44 UTC, jmleroux approved these changes

2020-11-10 08:49 UTC, merged