RAC-464: Use illu as svg
akeneo/pim-community-dev pull request #13728
Opened 2021-01-14 10:47 UTC by ValentinMumble

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2021-01-14 12:22 UTC, StevenVAIDIE requested changes
NOT GTM you should do all the illustration

2021-01-15 10:04 UTC, juliensnz approved these changes

2021-01-15 10:32 UTC, StevenVAIDIE approved these changes
My computer does not freeze anymore when i load this page, please do not merge this PR :pray:

2021-01-15 10:32 UTC, StevenVAIDIE commented on akeneo-design-system/static/illustrations/Export.svg
> +                        <path d="M25.6338,32.176 C26.0598,32.579 26.4688,33.063 26.8948,33.566 C27.1808,33.905 27.4748,34.252 27.7788,34.578 C32.7188,31.958 32.7488,28.431 32.7288,27.163 C32.1668,26.
```suggestion
                        <path d="M25.6338,32.176 C26.0598,32.579 26.4688,33.063 26.8948,33.566 C27.1808,33.905 27.4748,34.252 27.7788,34.578 C32.7188,31.958 32.7488,28.431 32.7288,27.163 C32.1668,26.481 31.0578,25.408 30.1648,24.604 C30.2838,28.53 27.0088,31.222 25.6338,32.176 L25.6338,32.176 Z M27.5748,35.803 L27.3208,35.545 C26.8998,35.119 26.5088,34.657 26.1308,34.211 C25.5678,33.545 25.0338,32.916 24.5008,32.526 L23.8738,32.068 L24.5508,31.687 C24.6078,31.655 30.1258,28.485 29.0208,23.485 L28.7138,22.096 L29.8218,22.987 C30.6758,23.956 32.8208,25.645 33.6208,26.679 L33.7238,26.811 L33.7258,26.978 C33.7928,30.791 31.8318,33.672 27.8998,35.641 L27.5748,35.803 Z" id="Fill-97" fill="#52267D"></path>
```

2021-01-15 10:40 UTC, ValentinMumble commented on akeneo-design-system/static/illustrations/Export.svg
> +                        <path d="M25.6338,32.176 C26.0598,32.579 26.4688,33.063 26.8948,33.566 C27.1808,33.905 27.4748,34.252 27.7788,34.578 C32.7188,31.958 32.7488,28.431 32.7288,27.163 C32.1668,26.
Ah yes thank you!!!! Of course!

2021-01-15 16:49 UTC, merged