PIM-9664: Add fallback URL for product images
akeneo/pim-community-dev pull request #13902
Opened 2021-02-10 15:55 UTC by anaisbaunelemaire

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2021-02-10 16:00 UTC, tomglvng approved these changes

2021-02-10 16:33 UTC, olivierpontier requested changes
Could you update the changelog please?

2021-02-11 09:13 UTC, anaisbaunelemaire commented
> Could you update the changelog please?

The changelog is in the EE PR. Do I have to update it here, too?

2021-02-15 10:49 UTC, olivierpontier approved these changes

2021-02-15 10:54 UTC, merged