PIM-9750: Auto_increment reaches max value for pim_catalog_completeness table
akeneo/pim-community-dev pull request #14115
Opened 2021-03-18 14:05 UTC by tomglvng

2021-03-18 14:43 UTC, LaurentPetard approved these changes

2021-03-19 14:56 UTC, nmarniesse approved these changes

2021-03-19 14:56 UTC, nmarniesse commented on CHANGELOG-4.0.md
> +## Bug fixes
Should be before the `# 4.0.98 (2021-03-16)` line

2021-03-19 15:04 UTC, BitOne requested changes
How to make sure this PR will

2021-03-19 15:04 UTC, BitOne commented on upgrades/schema/Version_4_0_202103181422_update_pim_catalog_completeness_id.php
> +final class Version_4_0_202103181422_update_pim_catalog_completeness_id extends AbstractMigration
No migration on released version.

2021-03-19 15:11 UTC, fitn commented on upgrades/schema/Version_4_0_202103181422_update_pim_catalog_completeness_id.php
> +final class Version_4_0_202103181422_update_pim_catalog_completeness_id extends AbstractMigration
@BitOne Please suggest a solution

2021-03-22 08:04 UTC, BitOne approved these changes

2021-03-22 10:05 UTC, merged