PIM-9726: mitigate deadlock on categories (backport PIM-9548)
akeneo/pim-community-dev pull request #14204
Opened 2021-03-31 10:20 UTC by willy-ahva

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | OK
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | OK
| Changelog updated                 | OK
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2021-03-31 12:13 UTC, BitOne requested changes
Why do we apply a different solution than usual with deadlock?

2021-03-31 12:26 UTC, ahocquard commented on upgrades/schema/Version_4_0_20210331092434_add_lock_table.php
> +CREATE TABLE lock_keys (
To create on the fly:
```suggestion
CREATE TABLE IF NOT EXISTS lock_keys (
```

2021-04-01 10:06 UTC, ahocquard approved these changes
I would put directly the creation of the table inside the CategorySaver instead of wrapping it in a class + interface.

But as it will not be pull up it's ok.

2021-04-01 10:06 UTC, ahocquard commented on src/Akeneo/Pim/Enrichment/Component/Lock/Query/EnsureLockTableExistsInterface.php
> +interface EnsureLockTableExistsInterface
useless interface but not a big deal as it should not be pulled up

2021-04-01 14:44 UTC, BitOne approved these changes

2021-04-02 07:36 UTC, merged