API-1549: Event logs - filter refresh
akeneo/pim-community-dev pull request #14271
Opened 2021-04-15 10:16 UTC by tomglvng

2021-04-15 10:29 UTC, pchasle commented on src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx
> +        sessionStorage.setItem('filters', JSON.stringify(filters));
We might want to have a more specific key as the session storage is shared by the whole application.
Something like `connectivity_connection_event_subscription_logs_filters`

2021-04-15 15:30 UTC, tseho requested changes
(i'm going to develop later today)

2021-04-15 20:17 UTC, tseho commented on src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx
> +    const sessionFilters = sessionStorage.getItem('connectivity_connection_event_subscription_logs_filters');
by loading here, you are loading from the sessionStorage everytime you render the component.
FYI, with the current state of our hooks, when you load this page for the first time, it's re-rendered up to 8 times !

You should extract it to another function, for eg:
```
const loadFiltersFromTheSession = () => {
  const stored = sessionStorage.getItem('connectivity_connection_event_subscription_logs_filters');
  
  return null !== stored ? JSON.parse(stored) : null;
}
const saveFiltersIntoTheSession = (filters) => {
  sessionStorage.setItem('connectivity_connection_event_subscription_logs_filters', JSON.stringify(filters));
}

export const EventLogList: FC<{connectionCode: string}> = ({connectionCode}) => {
  // ...
  const [filters, setFilters] = useState<{
        filters: EventSubscriptionLogFilters;
  }>(loadFiltersFromTheSession() || getDefaultFilters());
  // ...
```

2021-04-16 09:22 UTC, tseho approved these changes

2021-04-16 14:06 UTC, RiffVentura approved these changes

2021-04-16 14:22 UTC, pchasle approved these changes

2021-04-16 15:14 UTC, merged