PIM-9801: Fix jobs that are still stuck in STARTED and STOPPING and c…
akeneo/pim-community-dev pull request #14287
Opened 2021-04-16 14:22 UTC by willy-ahva

…reate a command to avoid this again

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2021-04-19 14:05 UTC, pchasle approved these changes

2021-04-19 14:05 UTC, pchasle commented on src/Akeneo/Tool/Bundle/BatchBundle/Command/MarkJobExecutionAsFailedWhenInterruptedCommand.php
> +            'When jobs are launched with the if an error happen the job execution crashes and need to be cleaned.'
It look like it's missing a part of the sentence "launched with the ... if"

2021-04-19 14:40 UTC, LaurentPetard commented on src/Akeneo/Tool/Bundle/BatchBundle/Command/MarkJobExecutionAsFailedWhenInterruptedCommand.php
> +            'When jobs are launched with the if an error happen the job execution crashes and need to be cleaned.'
Indeed. Fixed

2021-04-20 07:52 UTC, StevenVAIDIE requested changes
We need to wrap the rule cron script in a wrapper like Mathias and Alexandre sayed here: https://github.com/akeneo/pim-enterprise-dev/pull/10675#issuecomment-821068305. Without this, the support/SRE team will have to launch the command every month

2021-04-20 07:52 UTC, StevenVAIDIE commented on upgrades/schema/Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted.php
> +final class Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted extends AbstractMigration
This migration should be in EE because it's concern only EE job ?

2021-04-20 07:53 UTC, LaurentPetard commented on upgrades/schema/Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted.php
> +final class Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted extends AbstractMigration
Yes you're right, it's for two jobs that only exist on EE

2021-04-20 08:44 UTC, fitn commented on upgrades/schema/Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted.php
> +final class Version_6_0_20210415130338_mark_job_execution_as_failed_when_interrupted extends AbstractMigration
Hello Steven, yes that's the plan to launch this command on demand. Another ticket will be done by BH squad to make it cleaner.
Our main goal is to unlock the customer issue ;)

2021-04-20 12:14 UTC, StevenVAIDIE approved these changes

2021-04-22 13:17 UTC, merged