Cpm 165 Tags component for the DSM
akeneo/pim-community-dev pull request #14435
Opened 2021-05-06 15:58 UTC by adrienwb

**Description (for Contributor and Core Developer)**

https://www.notion.so/akeneo/Tags-chipmunks-in-progress-3ebdd3deff314ee7b2144aac24ab7ab7

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-05-06 16:28 UTC, pierallard requested changes

2021-05-06 16:28 UTC, pierallard commented on front-packages/akeneo-design-system/src/components/Tags/Tags.unit.tsx
> +// and you will need to add these required props here as well
You can remove this comment

2021-05-06 17:04 UTC, adrienwb commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +  font-size: 11px;
will change to:
  font-size: ${getFontSize('small')};

2021-05-06 17:04 UTC, adrienwb commented on front-packages/akeneo-design-system/src/components/Tags/Tags.unit.tsx
> +// and you will need to add these required props here as well
will do, thx

2021-05-06 17:54 UTC, juliensnz approved these changes
Really small comment (not even mandatory). Thanks a lot for this contribution. Much appreciated to see contribs from management :trumpkiss:

2021-05-06 17:54 UTC, juliensnz commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +      React.Children.map(children, child => {
Using a map with a non pure function is not advised. I would suggest to do this instead:

React.children.filter(/* check if string*/).join('')

2021-05-07 07:19 UTC, ValentinMumble commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +              title: tag.props?.title || getTitle(tag.props?.children),
Instead of casting as `ReactElement`, I'd create a `TagProps` above for the `Tag` component type and pass it to the `isValidElement` function like this
```suggestion
          if (isValidElement<TagProps>(child) && child.type === Tag) {
            return React.cloneElement(child, {
              title: child.props?.title || getTitle(child.props?.children),
```

2021-05-07 07:21 UTC, ValentinMumble commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +  {tint: 'green' | 'blue' | 'dark_blue' | 'purple' | 'dark_purple' | 'yellow' | 'red'} & AkeneoThemedProps
```suggestion
type Tint = 'green' | 'blue' | 'dark_blue' | 'purple' | 'dark_purple' | 'yellow' | 'red';
type TagProps = {
  tint: Tint;
} & React.HTMLAttributes<HTMLLIElement>;
const Tag = styled.li<TagProps & AkeneoThemedProps>`;
```
Extending the `HTMLAttributes<HTMLLIElement>` will allow you to get the `title` prop you use later 😉

2021-05-07 07:23 UTC, ValentinMumble commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +      React.Children.map(children, child => {
Indeed but the `React.Children.map` is a bit smarter than the `Array.map`, to use `.filter()` you'd have to convert your children `.toArray()` first

2021-05-07 07:25 UTC, ValentinMumble commented on front-packages/akeneo-design-system/src/components/index.ts
> +export * from './Tags/Tags';
In order for your component to be in the right position here https://akeneo.github.io/akeneo-design-system/14435/?path=/story/introduction--page, you have to order it alphabetically here in the exports 🙂

2021-05-07 07:26 UTC, ValentinMumble approved these changes

2021-05-07 12:56 UTC, ValentinMumble commented on front-packages/akeneo-design-system/src/components/Tags/Tags.tsx
> +import {AkeneoThemedProps, getFontSize} from 'theme';
```suggestion
import {AkeneoThemedProps, getFontSize} from '../../theme';
```
I believe this is why the example integration tests are failing https://github.com/akeneo/pim-community-dev/pull/14435/checks?check_run_id=2527324434, we cannot use absolute imports in the DSM 😉

2021-05-31 07:39 UTC, pierallard approved these changes

2021-05-31 07:39 UTC, merged