PLG-243: Enable Appcuses onboarding for the FT
akeneo/pim-community-dev pull request #14579
Opened 2021-05-26 16:14 UTC by olivierpontier

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-05-26 16:22 UTC, AymericPlanche requested changes

2021-05-26 16:22 UTC, AymericPlanche commented on src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
> +    pim/onboarding: akeneofreetrial/js/onboarding/appcuses-onboarding.ts
```suggestion
    pim/onboarding: akeneofreetrial/js/onboarding/appcues-onboarding.ts
```

2021-05-26 16:22 UTC, AymericPlanche commented on src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcuses-onboarding.ts
> +        email: UserContext.get('email'),
do not send email to appcues to ease RGPD compliancy. 
the only unique user identifier must be the PIM username.
you can pass other pim user related data but every "personnal" data must be challenged.

2021-05-26 16:22 UTC, AymericPlanche commented on src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcuses-onboarding.ts
> +const AppcuesOnBoarding: PimOnBoarding = {
```suggestion
const AppcuesOnboarding: PimOnboarding = {
```

no need to camelcase, it's a word ! ;)

2021-05-26 16:22 UTC, AymericPlanche commented on src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/onboarding/pim-onboarding.ts
> +const DefaultPimOnBoarding: PimOnBoarding = {
no camelcase (everywhere)

2021-05-26 16:22 UTC, AymericPlanche commented on src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcuses-onboarding.ts
> +        email: UserContext.get('email'),
we can discuss about it tomorrow ;)

2021-05-26 17:10 UTC, AymericPlanche approved these changes

2021-05-28 14:46 UTC, LaurentPetard approved these changes

2021-05-28 15:40 UTC, merged