CXP-713 Added MainNavigationItem component to DSM
akeneo/pim-community-dev pull request #14625
Opened 2021-06-02 09:03 UTC by RiffVentura

CXP-713 Added MainNavigationItem component to DSM

**Description (for Contributor and Core Developer)**

https://www.notion.so/akeneo/Navigation-Weasels-Octopus-ddadffaf49dd411b86dc0b3efb2eb071#fdac48636795435395bca185bfe753c2

**Definition Of Done (for Core Developer only)**

- [x] Tests
- [ ] Migration & Installer
- [] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-06-02 12:46 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +TODO
I think it should be provided by the UX team, I will ping Sophie

2021-06-02 13:12 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +TODO
Validated by the UX team:
`The Main Navigation Item is used by the Navigation pattern. This components helps the users in their daily usage as an easy way to discover and navigate the interface. Also, it's a companion for them to understand where they are in their journey.`

2021-06-04 08:39 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +                    <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} active={false} title='Default'/>
```suggestion
                    <MainNavigationItem {...args} icon={<CardIcon/>} active={false} title='Default'/>
```
Why are not using this syntax ?

2021-06-04 08:40 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.tsx
> +          {React.cloneElement(icon, {size: 20})}
Do you need to clone here ? Why ?

2021-06-04 08:40 UTC, pchasle commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +      return <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} />;
Same comment as a SubNavigationItem on the component "API"
Maybe something like that:
```tsx
<MainNavigationItem icon={<AnIcon />} tag={<Tag tint='purple'>👋</Tag>}>
  Hello world!
</MainNavigationItem>
```

2021-06-04 08:42 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.tsx
> +  top: -35%;
I would rather have pixel positions, I don't trust `%` enough for positioning precisely.

2021-06-04 08:43 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.tsx
> +const CustomTag = styled(Tag)`
```suggestion
const PositionedTag = styled(Tag)`
```
what do you think of this ? `Custom` is not clear about what your component changes

2021-06-04 08:44 UTC, tseho commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +                    <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} tag='new'/>
Same here, what do you think of this syntax:
```suggestion
                    <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} tag={<Tag .../>}/>
```

2021-06-04 08:47 UTC, tseho commented
Also, should this component live in a `Navigation` folder ? like we did for Buttons & Inputs.

2021-06-04 08:49 UTC, RiffVentura commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +                    <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} active={false} title='Default'/>
Because storybook contain a selector for the icon preview (Playground args table)

2021-06-04 08:52 UTC, RiffVentura commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.tsx
> +          {React.cloneElement(icon, {size: 20})}
I needed to overwrite icon size, and it the only way I know to update props from receiving JSX

2021-06-04 08:53 UTC, pchasle commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +      return <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} />;
or like this, since Tag is optionnal
```tsx
<MainNavigationItem icon={<AnIcon />}>
  Hello world!
  <Tag tint='purple'>👋</Tag>
</MainNavigationItem>
```

2021-06-04 09:02 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +      return <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} />;
```
<MainNavigationItem icon={<AnIcon />}>
  Hello world!
  <MainNavigationItem.Tag tint='purple'>👋</MainNavigationItem.Tag>
</MainNavigationItem>
```

2021-06-04 09:05 UTC, juliensnz requested changes
I thinks we should discuss it if we want to merge it like that as it's quite different from the other existing components in the DSM. I'm open to discuss it if we want to change things in the DSM but we need to make sure we will stick to it next.

2021-06-04 09:05 UTC, juliensnz commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.tsx
> +  onClick?: (event: SyntheticEvent) => void;
What do you think about handling the links like that: https://github.com/akeneo/pim-community-dev/blob/master/front-packages/akeneo-design-system/src/components/Dropdown/Item/Item.tsx#L94

This way, you will avoid having to manage the link directly

2021-06-04 09:10 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/MainNavigationItem/MainNavigationItem.stories.mdx
> +                    <MainNavigationItem {...args} icon={React.createElement(Icons[args.icon])} active={false} title='Default'/>
The playground args table only change the Playground story

2021-06-11 14:58 UTC, StevenVAIDIE approved these changes

2021-06-11 14:58 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.stories.mdx
> +            Purple <Tag tint="purple">Lengthy tag that take way too much space</Tag>
It seem that tag is hidden by overflow hidden it's normal ? 
![Screenshot from 2021-06-11 16-46-46](https://user-images.githubusercontent.com/7239572/121705188-b2687600-cad4-11eb-98f4-0b2510fa1e58.png)

2021-06-11 14:58 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.stories.mdx
> +import {Meta, Story, ArgsTable, Canvas} from '@storybook/addon-docs/blocks';
You can remove unnecessary image_snapshot (you have changed the path of the story)

- front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-main-navigation-item-standard-correctly-1-snap.png
- front-packages/akeneo-design-system/src/__image_snapshots__/all-visual-tsx-visual-tests-renders-components-main-navigation-item-tag-correctly-1-snap.png

2021-06-11 14:58 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.tsx
> +      }
We often this syntax now, I don't know what do you think about :

```suggestion
      onClick?.(event);
```

2021-06-11 15:07 UTC, pchasle commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.stories.mdx
> +            Purple <Tag tint="purple">Lengthy tag that take way too much space</Tag>
Yes. It's validated like this by Sébastien (UX). The text in the tag should not really be more than 3 characters and should not overflow.
We can't easily add an ellipsis `...` on the text since it's managed by the Tag component directly (or maybe with some modifications on it?!) but even then, the space taken by the ellipsis will only allow to display 2 characters ...

2021-06-11 15:08 UTC, pchasle commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.tsx
> +      }
I didn't event know you could use optional chaining on function call :+1: will update

2021-06-11 15:13 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.stories.mdx
> +            Purple <Tag tint="purple">Lengthy tag that take way too much space</Tag>
:ok_hand: it's just to be sure. If it's clear with UX no problem :slightly_smiling_face:

2021-06-14 13:56 UTC, juliensnz approved these changes

2021-06-14 13:59 UTC, tseho commented on front-packages/akeneo-design-system/src/components/index.ts
> +export * from './Tiles/Tiles';
```suggestion
```

2021-06-14 13:59 UTC, tseho approved these changes
GTM after fix

2021-06-14 15:03 UTC, merged