API-1659 Setup RequestContext with missing host
akeneo/pim-community-dev pull request #14720
Opened 2021-06-14 15:27 UTC by RiffVentura

Added  host configuration to the RequestContext of the router 

**Description (for Contributor and Core Developer)**

Routing  defaults  to localhost inside a consumer. To mitigate this issue, a setup for the RequestContext was added

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-06-16 08:17 UTC, pchasle commented on src/Akeneo/Platform/Bundle/FrameworkBundle/Service/PimUrl.php
> +class PimUrl
I think that it will be better to have the service expose the host, scheme, port directly.
Easier to test the parsing of the URL and easier to use.

2021-06-16 13:11 UTC, tseho commented on src/Akeneo/Platform/Bundle/FrameworkBundle/Service/PimUrl.php
> +class PimUrl
Additionally to the url ?
I don't know if that makes sense, most of the time, when you use it, you want the url, you don't want to check if there is a port in it for example.

To me, the signature of the service make sense as it is.
In the `boot`, yes, we have to explode it because it's in the `boot` method that we bridge between the full url and the router context who want the individual parts.

2021-06-16 13:16 UTC, tseho commented
Don't forget to open a PR in EE too, you need to declares it in EE bundles.php too

2021-06-16 14:12 UTC, pchasle commented on src/Akeneo/Platform/Bundle/FrameworkBundle/Service/PimUrl.php
> +class PimUrl
It's better than having to explode the url each time to get exactly what we need.
We can expose the whole url too or let the user of this service reconstruct the url by itself

2021-06-17 08:06 UTC, pchasle approved these changes

2021-06-17 09:49 UTC, tomglvng approved these changes

2021-06-17 12:37 UTC, willy-ahva approved these changes

2021-06-17 14:27 UTC, tseho commented on src/Akeneo/Platform/Bundle/FrameworkBundle/Service/PimUrl.php
> +class PimUrl
> It's better than having to explode the url each time to get exactly what we need.
There is no such thing. AFAIK, this is the only place in the PIM where the AKENEO_PIM_URL is exploded.
All the other places I've seen, even in the Events API, the url is used without manipulation.
Since we are thinking on the long term, in a soon future, this environment variable will disappear and every service will have to call a service like this one to access the URL of the PIM.
I don't want to force all the other use cases to glue the url because there was one place where we wanted the parts.

2021-06-17 20:20 UTC, tseho requested changes

2021-06-17 20:20 UTC, tseho commented on config/bundles.php
> +    Akeneo\Platform\Bundle\FrameworkBundle\PimFrameworkBundle::class => ['all' => true]
You broke growth edition by leaving-out the trailing `,`

When merging the bundles.php in GE, it look like this:
```
Akeneo\FreeTrial\Infrastructure\Symfony\AkeneoFreeTrialBundle::class =>  ['all' => true],
Akeneo\Platform\Bundle\FrameworkBundle\PimFrameworkBundle::class => ['all' => true]
Akeneo\Platform\Bundle\MonitoringBundle\AkeneoMonitoringBundle::class => ['all' => true],
```
Which is not valid php, breaking the build of GE.

2021-06-18 07:49 UTC, RiffVentura commented on config/bundles.php
> +    Akeneo\Platform\Bundle\FrameworkBundle\PimFrameworkBundle::class => ['all' => true]
facepalm

2021-06-18 08:12 UTC, tseho commented on config/bundles.php
> +    Akeneo\Platform\Bundle\FrameworkBundle\PimFrameworkBundle::class => ['all' => true]
> facepalm

No, no 😅
It's not your fault, 
1) we should have better tools to enforce code style
2) we should build GE differently

2021-06-18 08:12 UTC, tseho approved these changes

2021-06-21 13:08 UTC, merged