RAC-609: Fix multi-select-input bug when cades don't have associated children
akeneo/pim-community-dev pull request #14747
Opened 2021-06-17 08:29 UTC by SamirBoulil

**Description (for Contributor and Core Developer)**

This PR fixes an issue occuring on the multi select input when one of the codes of the options given for the multi select does not exist as an Option in the Children

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-06-18 09:32 UTC, StevenVAIDIE requested changes

2021-06-18 09:32 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
> +          value={value.map(chipCode => indexedChips[chipCode] ?? {code: chipCode, label:chipCode})}
```suggestion
          value={value.map(chipCode => indexedChips[chipCode] ?? {code: chipCode, label: chipCode})}
```

Maybe add a test about it the added test do not test it ?

2021-06-18 09:58 UTC, StevenVAIDIE approved these changes

2021-06-18 14:13 UTC, pierrejolly approved these changes

2021-06-23 11:06 UTC, SamirBoulil commented on front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
> +          value={value.map(chipCode => indexedChips[chipCode] ?? {code: chipCode, label:chipCode})}
fixed

2021-06-23 13:54 UTC, SamirBoulil commented
refresh frozen

2021-06-24 07:33 UTC, SamirBoulil commented
refresh

2021-06-24 08:20 UTC, merged