CXP-359: Update error message - The %attribute% attribute requires an equal or greater than %min_value% value.
akeneo/pim-community-dev pull request #14811
Opened 2021-06-23 08:14 UTC by tomglvng

2021-06-23 09:04 UTC, romaindak commented on tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RangeValidatorSpec.php
> +        $this->validate( 9.99999, $constraint);
```suggestion
        $this->validate(9.99999, $constraint);
```

2021-06-23 09:06 UTC, romaindak approved these changes

2021-06-23 09:06 UTC, RiffVentura approved these changes

2021-06-23 09:35 UTC, tomglvng commented on tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RangeSpec.php
> +    function it_has_an_min_message()
```suggestion
    function it_has_a_min_message()
```

2021-06-23 09:38 UTC, tomglvng commented on tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RangeSpec.php
> +        $this->beConstructedWith(['max' => new \DateTime()]);
```suggestion
         $this->beConstructedWith(['min' => 1]);
```

2021-06-23 09:54 UTC, pchasle requested changes

2021-06-23 09:54 UTC, pchasle commented on src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php
> +            case is_numeric($value) && $value < $constraint->min:
This doesn't work, `$constraint->min` can be null.

2021-06-23 10:02 UTC, pchasle commented on src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php
> +            case is_numeric($value) && $value < $constraint->min:
I don't think that you should use `validateData` either, this is defined for `Metric` or `ProductPrice` as specified in the comment (the `->atPath('data')` would not be valid for a simple scalar value).

I will suggest to do something like that https://github.com/akeneo/pim-community-dev/pull/14798/files#diff-6c4337f1523f1a32e45b45efe4b0a06a2b2c05a42f6ad44cb28ad65d72708440R26
To rebuild the constraint with our own message.

2021-06-23 10:04 UTC, pchasle commented on src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php
> +            case is_numeric($value) && $value < $constraint->min:
You still need to keep your changes in the violation of `validateData` though for `Metric` and `ProductPrice` though :)

2021-06-24 14:25 UTC, tomglvng commented on src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php
> +            case is_numeric($value) && $value < $constraint->min:
See changes in https://github.com/akeneo/pim-community-dev/pull/14811/commits/e584a25dea485a1f7f30dcef2dc6a5a474bfef65

2021-06-24 14:27 UTC, tomglvng commented on src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php
> +            $violation->addViolation();
Yep, atPath() is used when value comes from an object ; here, it is just a scalar.

2021-06-24 14:31 UTC, romaindelouard approved these changes

2021-06-24 14:37 UTC, RiffVentura approved these changes

2021-06-24 15:56 UTC, pchasle approved these changes

2021-06-25 08:56 UTC, merged