CXP-788 : Fetch data from marketplace API (mock implementation)
akeneo/pim-community-dev pull request #14895
Opened 2021-07-02 14:39 UTC by tomglvng

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-07-02 16:22 UTC, pchasle commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/GetAllExtensionsQueryInterface.php
> +namespace Akeneo\Connectivity\Connection\Domain\Marketplace;
What do you think about having:

Common DTO for an extension, maybe it's fine for now, or maybe it should be specific to and live with the query.
```php
namespace Akeneo\Connectivity\Connection\Domain\Marketplace\DTO;

class Extension
{
}
```

Folder `GetAllExtensionsQuery` that host the query interface and the response object:

```php
namespace Akeneo\Connectivity\Connection\Domain\Marketplace\Query\GetAllExtensions;

use Akeneo\Connectivity\Connection\Domain\Marketplace\DTO\Extension;

class ExtensionList
{
    /** @var array<Extension> */
    private array $extensions;
}
```
```php
namespace Akeneo\Connectivity\Connection\Domain\Marketplace\Query\GetAllExtensions;

interface GetAllExtensionsQueryInterface
{
    public function execute(): ExtensionList;
}
```

2021-07-02 16:25 UTC, pchasle commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
> +      - '@database_connection'
Please, do not change the indentation. It's 4 spaces for yaml files.

2021-07-05 09:56 UTC, tseho approved these changes

2021-07-05 09:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +namespace Akeneo\Connectivity\Connection\Domain\Marketplace\DTO;
In the present case, `Extension` is not a DTO, it's our model.
IHMO, It should be in `Domain\Marketplace\Model`, like the other Connectivity models.

2021-07-05 09:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +use Ramsey\Uuid\UuidInterface;
What's the value of using Ramsey\Uuid here ?

2021-07-05 09:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +        );
You want a neat trick to avoid declaring twice your properties, both in named constructor `create(...)` and in the default constructor ?

Since you are inside the class, you can skip the constructor and do it like this:
```
class Extension
{
    private string $name;
    
    public static function create(array $values): self
    {
        $self = new self();
        $self->name = $values['name'];
        
        return $self;
    }
```

2021-07-05 09:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/GetAllExtensionsQueryInterface.php
> +namespace Akeneo\Connectivity\Connection\Domain\Marketplace;
This is an interesting proposition but I'm not seeing the immediate value, and more than anything, it will change **again** how we declare stuff in the domain.

If we want it, we need to think & discuss seriously about it and refactor accordingly all of Connectivity domains at once for consistency.

This is out of scope for the current PR.

2021-07-05 09:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
> +        $container->setParameter('connectivity.marketplace_fixtures_directory', __DIR__ . '/../Resources/fixtures/');
why there ?
Can't you use `__DIR__`directly in WebMarketplaceApi to locate the file ?

I'm not seeing the benefit of creating a parameter for it.

2021-07-05 12:28 UTC, tomglvng commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +use Ramsey\Uuid\UuidInterface;
Consistency with returned data: the 'id' is an UUID.

2021-07-05 12:35 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +use Ramsey\Uuid\UuidInterface;
Here https://github.com/akeneo/pim-community-dev/blob/53fc71fa21e13b860ee57baf2ffcfbe5f505ea91/src/Akeneo/Platform/Component/EventQueue/EventInterface.php#L21
It's also an UUID, an UUID can be represented by a string.

What's our deal with UUID in `Extension` ? are we generating UUIDs ? do we need to validate UUIDs ?
Or this ID is simply a string we don't event have to type ?

2021-07-05 12:40 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +use Ramsey\Uuid\UuidInterface;
Moreover, `Ramsey\Uuid\UuidInterface` is not a domain VO, it's an external interface.
By doing so, you are coupling your domain to an external library, which against our decoupling principles.

2021-07-05 13:33 UTC, tomglvng commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
> +        $container->setParameter('connectivity.marketplace_fixtures_directory', __DIR__ . '/../Resources/fixtures/');
In case we want to redefine the service but need another fixture path directory (tests for example), this way of doing is enough flexible.

2021-07-06 07:35 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
> +        $container->setParameter('connectivity.marketplace_fixtures_directory', __DIR__ . '/../Resources/fixtures/');
The fixtures are a temporary thing for the marketplace extensions.
You can merge anyway, but when adding stuff like "maybe we will need to use it one day in tests even if we don't use today", you pile up technical debt. 
IMHO, it's easier to keep things simple (without sacrificing quality) and wait for the day where we need to customize this, if it happens.

2021-07-06 07:39 UTC, tseho commented
Can you also add the missing rules in https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
regarding this new Domain ?

2021-07-06 11:50 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/fixtures/marketplace-data-extensions.json
> +    "count": 120,
```suggestion
    "total": 120,
```

The marketplace spec explicitely specify `total`

2021-07-06 12:03 UTC, tomglvng commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/fixtures/marketplace-data-extensions.json
> +    "count": 120,
Sometimes it was `count` in our code, other `total`. I will harmonize with 'total' so

2021-07-06 12:05 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/fixtures/marketplace-data-extensions.json
> +    "count": 120,
yes, but here, it's the mock for the marketplace endpoint, if we don't follow the format of the marketplace API, we will hit a wall :sweat_smile:

2021-07-06 12:05 UTC, pchasle commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/Extension.php
> +use Ramsey\Uuid\UuidInterface;
Yes, I agree with Quentin, keep it decoupled and simple (string is fine). We generally only add VO when needed.

2021-07-06 12:17 UTC, tseho requested changes
After discussion, plz remove `Ramsey\Uuid` from our domain.
A simple `string` is enough, there is no need for a Value Object for now.

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/ExtensionList.php
> +namespace Akeneo\Connectivity\Connection\Domain\Marketplace\Model;
Should it really be in the Model namespace?

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +    public static function create(array $values): self
A named constructor is a very good idea, but the name should reflect the intent. If you use `create` you describe nothing more than a public constructor. Here I would prefer a name like `fromWebMarketplaceValues`

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +    public function id(): UuidInterface
If you don't need all those getters, please don't add them. (And use the template `getSomething` for getters).

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +    public function normalize(): array
just an idea, but shouldn't we use `toArray()` instead of `normalize`?

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +            Assert::keyExists($values, $key);
Use your own Domain Exception, please.

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/GetAllExtensionsQuerySpec.php
> +    )
on 1 line please

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/GetAllExtensionsQuerySpec.php
> +    {
1 line

2021-07-06 12:43 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/GetAllExtensionsQuerySpec.php
> +    public function it_execute_and_returns_extension_result(
```suggestion
    public function it_executes_and_returns_extension_result(
```

2021-07-06 12:53 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/ExtensionList.php
> +namespace Akeneo\Connectivity\Connection\Domain\Marketplace\Model;
What about an typed array for `ExtensionList` and keeping the model for `Extension` ?

2021-07-06 12:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +    public function id(): UuidInterface
It's where this model is falling apart, we don't even use its getters.
We construct an object, then normalize before serializing it for the API Response.

2021-07-06 15:56 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +            Assert::keyExists($values, $key);
I've thrown a simple InvalidArgument instead.

2021-07-06 16:09 UTC, tseho approved these changes

2021-07-06 16:37 UTC, willy-ahva approved these changes

2021-07-06 16:37 UTC, willy-ahva commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +class Extension
final

2021-07-06 19:18 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/Extension.php
> +class Extension
I can't, it break the specs.

2021-07-07 12:18 UTC, merged