PIM-10002: Pull-up 5.0 -> Master
akeneo/pim-community-dev pull request #15118
Opened 2021-08-16 10:28 UTC by LaurentPetard

2021-08-16 10:40 UTC, ValentinMumble approved these changes
GTM after handling master TODOs 😉

2021-08-16 10:40 UTC, ValentinMumble commented on src/Akeneo/Channel/Bundle/EventListener/ChannelLocaleSubscriber.php
> +     * TODO On merge master remove $commandLauncher
👀

2021-08-16 11:30 UTC, rfauglas requested changes
handle TODOs ;-)

2021-08-16 11:30 UTC, rfauglas commented on tests/back/Channel/Specification/Bundle/EventListener/ChannelLocaleSubscriberSpec.php
> +    // TODO Remove this test on merge master
Remove?

2021-08-16 11:30 UTC, rfauglas commented on tests/back/Channel/Specification/Bundle/EventListener/ChannelLocaleSubscriberSpec.php
> +    // TODO Remove this test on merge master
Same as above?

2021-08-17 08:33 UTC, rfauglas approved these changes

2021-08-17 14:17 UTC, merged