PIM-10123: Merge 5.0 into master
akeneo/pim-community-dev pull request #15612
Opened 2021-11-02 16:21 UTC by anaisbaunelemaire

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-11-02 16:31 UTC, nmarniesse approved these changes

2021-11-03 08:42 UTC, anaisbaunelemaire commented
warm

2021-11-03 09:39 UTC, rfauglas requested changes

2021-11-03 09:39 UTC, rfauglas commented on upgrades/schema/Version_5_0_20211018134301_migrate_longtext_to_json.php
> +final class Version_5_0_20211018134301_migrate_longtext_to_json extends AbstractMigration
Are we sure we keep it like that? a new migration marked as  5.0 on master?

2021-11-03 09:43 UTC, anaisbaunelemaire commented on upgrades/schema/Version_5_0_20211018134301_migrate_longtext_to_json.php
> +final class Version_5_0_20211018134301_migrate_longtext_to_json extends AbstractMigration
Good remark, I'll investigate!

2021-11-03 10:15 UTC, nmarniesse commented on upgrades/schema/Version_5_0_20211018134301_migrate_longtext_to_json.php
> +final class Version_5_0_20211018134301_migrate_longtext_to_json extends AbstractMigration
Yes we need it. It's not a mandatory migration, there is no bug with/without it. So the migration is authorized in this case.   

So what is the purpose of this migration you may ask? It helps to standardize the database of old/new instance. In order to have the same column type. So in the future if we use a SQL json function in a query, we will not have error on old catalog

2021-11-03 10:23 UTC, anaisbaunelemaire commented on upgrades/schema/Version_5_0_20211018134301_migrate_longtext_to_json.php
> +final class Version_5_0_20211018134301_migrate_longtext_to_json extends AbstractMigration
@nmarniesse, I think that @rfauglas was talking about the class name, marked as 5.0. Isn't it?

2021-11-04 09:49 UTC, rfauglas approved these changes

2021-11-04 10:03 UTC, anaisbaunelemaire commented on src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
> +            if (null === $value || '' === $value) {
This modification was made as part of a bug fix:
https://github.com/akeneo/pim-community-dev/commit/cb430833688b6614f5b4004a51b156815143650a#diff-30028da9774e88fe7067c1cefeb4f1cb1995ed22ef26c983cee84a5a9a6be9b1

2021-11-04 10:04 UTC, anaisbaunelemaire commented
warm

2021-11-04 10:04 UTC, merged