PIM-10155: Optimize memory consumtion during product and product model indexation
akeneo/pim-community-dev pull request #15751
Opened 2021-11-22 16:48 UTC by mmetayer

**Description (for Contributor and Core Developer)**

This PR aims at diminishing the memory consumed during product and model indexation:
- try to duplicate as little as possible arrays containing raw_values during the generation of ES projections
- decrease the batch size from 1000 to 500

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2021-11-24 09:12 UTC, ahocquard requested changes
I'm not confident that the change reduces the memory footprint by two, when I see many duplicated variables. Also, too many not obvious trick for any PHP developer not knowing the memory management of PHP.
 
Are we sure it's not a regression introduced by the use of a context for table attribute?

I think that if we want to avoid trick, we must use reference. It will highlight that we don't want duplicated memory copy.

2021-11-24 09:12 UTC, ahocquard commented on src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
> +                'labels' => $productModelLabels,
the value collection is duplicated two times for the "context" variable (btw, `context` is a generic naming to avoid)

2021-11-30 12:58 UTC, mmetayer commented on src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilter.php
> -    }
This is already handled by [NonExistentChannelLocaleValuesFilter](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php)

2021-11-30 13:07 UTC, mmetayer commented on src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
> +                $productModelLabelValues = $row['values']->filter(
it does not work anyway, I removed it and let the more readable code instead

2021-11-30 13:07 UTC, mmetayer commented on src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
> +        $rows = \array_combine(
same

2021-11-30 13:12 UTC, mmetayer commented
@ahocquard after multiple tests I decided to let the code as it was before (modulo some really minor improvements). With really big products, the memory peak usage will happen during the `fetchAllAssociative()` anyway, so any further improvement in the `GetElasticsearchProduct[Model]Projection` classes are not useful

2021-11-30 14:25 UTC, willy-ahva approved these changes

2021-11-30 16:01 UTC, ahocquard approved these changes

2021-12-06 08:21 UTC, merged