PLG-757 harmonize dqi product id
akeneo/pim-community-dev pull request #16276
Opened 2022-02-09 16:14 UTC by antoinetrouve

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-02-09 16:37 UTC, nicometriau commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public static function fromInt(array $productIds): self
Takes an array as argument, so would gain to be called in plural form fromInts (same for fromProductId/fromProductIds).
Maybe someday we'll need a fromInt(int $productId), shortcut to create a ProductIds from a sole int. Naming current functions fromInts & fromProductIds would make us ready for that without refactoring.

2022-02-10 09:57 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public static function fromInt(array $productIds): self
done

2022-02-10 10:22 UTC, LaurentPetard approved these changes

2022-02-10 13:08 UTC, FSAkeneo commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public function addProductId(ProductId $productId): self
IT look like it mutates the receiver (this) but also create a new instance backed by the same array ?

2022-02-10 13:10 UTC, FSAkeneo commented on src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/ValueObject/ProductIdCollectionSpec.php
> +        $this->toArray()[3]->shouldBeAnInstanceOf(ProductId::class);
there is a reason why we can $this->toArray() five time instead of once ?

2022-02-11 16:03 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/ValueObject/ProductIdCollectionSpec.php
> +        $this->toArray()[3]->shouldBeAnInstanceOf(ProductId::class);
yep. the shouldBeAnInstanceOf() does'nt work with foreach scope.

2022-02-11 16:05 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public function addProductId(ProductId $productId): self
I do not know if immutability is necessary here.
@LaurentPetard ? could you explain why we have to use immutability concept for the add function pls ?

2022-02-11 16:10 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public function addProductId(ProductId $productId): self
Immutability is not mandatory, but a good practice. You can find many posts on the web about that.

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ComputeProductsKeyIndicators.php
> +        foreach ($productIdCollection->toArray() as $productId) {
ProductIdCollection is an Iterator, you can use it directly in a loop
```suggestion
        foreach ($productIdCollection as $productId) {
```

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateCriteriaEvaluations.php
> +     * @param ProductIdCollection $productIdCollection
Remove this PHPDOC it's useless now the the strict type

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateCriteriaEvaluations.php
> +        foreach ($productIdCollection->toArray() as $productId) {
```suggestion
        foreach ($productIdCollection as $productId) {
```

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluateProductModels.php
> +    public function __invoke(ProductIdCollection $productModelCollection): void
```suggestion
    public function __invoke(ProductIdCollection $productModelIdCollection): void
```

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluateProductModels.php
> +        $this->evaluatePendingProductModelCriteria->evaluateAllCriteria($productModelCollection);
```suggestion
        $this->evaluatePendingProductModelCriteria->evaluateAllCriteria($productModelIdCollection);
```

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductScoresQueryInterface.php
> +     * @param ProductIdCollection $productIdCollection
To remove

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
> +        $productIds = array_map(fn (ProductId $productId) => $productId->toInt(), $productIdCollection->toArray());
It would be nice to have a function `toArrayInt` in `ProductIdCollection` to do that

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        if (null === $productIdCollection) {
This condition is useless. `onPostSave`  doesn't return something

2022-02-11 16:40 UTC, LaurentPetard commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        return $productIdCollection;
Not needed

2022-02-11 17:16 UTC, olivierpontier commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public function addProductId(ProductId $productId): self
I agree with @FSAkeneo. Using immutability in a public instance method looks quite weird here and not appropriate for this case. As I understand with this method we want to manipulate an object which is a collection and we want to add a new item in it. Could you show us where we need to use this method and how we could use it, please? It should help us to understand and choose what is the best way to do it.

We can talk about it in our next technical daily :)

2022-02-11 17:22 UTC, olivierpontier commented
As @LaurentPetard said, adding a function to convert the ProductIdsCollection into an array of integer values could be a nice to have. The logic is used in several places: `array_map(fn (ProductId $productId) => $productId->toInt(), $productIdCollection->toArray()),`

2022-02-11 17:34 UTC, olivierpontier commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        if (null === $productIdCollection) {
I agree with @LaurentPetard, this condition at the end of the function looks useless. Did you add these lines for debugging purpose during the development? Or did you forget some code before commit?

2022-02-11 17:41 UTC, olivierpontier commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        return $productIdCollection;
It seems we do not use the collection of product ids after initializing the criteria.

2022-02-11 18:19 UTC, olivierpontier commented
As we can observe in several cases we need to cast the identifier value from a string into an integer before using ProductId value objects. What do you think about adding some `fromString` creation methods on `ProductId` and `ProductIdCollection` classes?
With this, we should be able to mutualize some cases like:
```
$nextProductIds = array_map(function ($resultRow) {
            return intval($resultRow['id']);
}, $stmt->fetchAllAssociative());
```     

and 

```
new ProductId(intval($param))
```

2022-02-11 18:29 UTC, olivierpontier requested changes
Good job!! It will be good to merge after some changes in comment

2022-02-14 11:13 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
> +    public function addProductId(ProductId $productId): self
In fact this function is useless for now. So I delete it.

2022-02-14 11:14 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ComputeProductsKeyIndicators.php
> +        foreach ($productIdCollection->toArray() as $productId) {
Done

2022-02-14 11:14 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateCriteriaEvaluations.php
> +     * @param ProductIdCollection $productIdCollection
Done

2022-02-14 11:14 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateCriteriaEvaluations.php
> +        foreach ($productIdCollection->toArray() as $productId) {
Done

2022-02-14 11:14 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluateProductModels.php
> +        $this->evaluatePendingProductModelCriteria->evaluateAllCriteria($productModelCollection);
Done

2022-02-14 11:14 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductScoresQueryInterface.php
> +     * @param ProductIdCollection $productIdCollection
Done

2022-02-14 11:15 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
> +        $productIds = array_map(fn (ProductId $productId) => $productId->toInt(), $productIdCollection->toArray());
Yes. I created this function and his test.

2022-02-14 11:17 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        if (null === $productIdCollection) {
Yes despite some change about using initializeCriteria() function this return is useless. I redefine the function signature to remove the return statement and the useless test in onPostSave function.

2022-02-14 11:17 UTC, antoinetrouve commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php
> +        return $productIdCollection;
Yes I remove it.

2022-02-14 12:58 UTC, BryanS29-akeneo approved these changes

2022-02-14 13:05 UTC, LaurentPetard approved these changes

2022-02-15 16:49 UTC, LaurentPetard requested changes
There are missing usage of `ProductIdCollection` that will throws errors during the execution of the jobs launched from CRONs.
At least here: https://github.com/akeneo/pim-community-dev/blob/cceddd94a9641c783afe552706f1673771a804a4/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/MarkCriteriaToEvaluate.php#L44
And here: https://github.com/akeneo/pim-community-dev/blob/cceddd94a9641c783afe552706f1673771a804a4/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php#L67

But it's not exhaustive, we need to explore and find all the occurrences.

2022-02-17 10:59 UTC, merged