OCT-10: add a more explicit violation message when the authorization code has expired
akeneo/pim-community-dev pull request #16369
Opened 2022-02-22 15:16 UTC by guillaumefer-akeneo

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-02-22 15:27 UTC, RiffVentura approved these changes

2022-02-23 14:02 UTC, guillaumefer-akeneo commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValidValidator.php
> +                $constraint->message,
ok, I made the change :)

2022-02-28 14:58 UTC, masacc approved these changes

2022-02-28 15:13 UTC, tseho requested changes
When doing it like this, you don't comply with the spec.
see https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

You need 2 separates keys.

```
{
  "error": "invalid_grant"
}
```
valid :heavy_check_mark: 

```
{
  "error": "invalid_grant",
  "error_description": "code has expired"
}
```
valid :heavy_check_mark: 

```
{
  "error": "invalid_grant: code has expired"
}
```
not valid :red_circle:

2022-04-28 13:44 UTC, tseho commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValidValidator.php
> +                ->addViolation();
feels weird to have 2 different violations here.
In which case do we have $authCode === null & a generic error message ?

2022-04-28 14:17 UTC, RiffVentura commented on src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValidValidator.php
> +                ->addViolation();
Auth code is stored (by the library)  just before redirection to the app callback URL 
So either we can't find one because the authorization code is invalid
Or it is already retrieved and marked as used
Do you think it is worth splitting into two different validators?

2022-05-17 07:44 UTC, masacc commented on src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Validation/AccessTokenRequestValidationIntegration.php
> +        \sleep(30);
This test adds 30 seconds in the CI... IMHO if there is no other way, we should not keep it. You did not find a way to change the TTL of the the auth code in a test context ? Maybe by updating it directly in the database ?

2022-05-20 07:44 UTC, RiffVentura commented
warm

2022-05-24 13:43 UTC, merged