PIM-10372: Fix letter case issue when importing channels
akeneo/pim-community-dev pull request #16688
Opened 2022-03-28 07:25 UTC by LaurentPetard

Locale codes of channel labels translations could be persisted with a different letter case that the (good) one persisted in the locales table.

This fix prevent that problem by replacing the locale code with the locale entity one during the data conversion from flat to standard.

2022-03-28 08:38 UTC, FSAkeneo approved these changes

2022-03-28 11:35 UTC, ahocquard requested changes
It's still possible to do it with the API, so the fix is not valid.

- in updater layer
- or why don't we fix the translation issue itself? As the table is case insensitive, the issue should be on PHP layer, doing a case sensitive comparison somewhere.

2022-03-28 12:21 UTC, docteurklein commented
or we could use mysql collations? https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html

2022-03-30 09:25 UTC, FSAkeneo commented
I'm closing in favor of https://github.com/akeneo/pim-community-dev/pull/16707

2022-03-30 09:25 UTC, closed without merging