PLG-783 simplify useFetchProductScores
akeneo/pim-community-dev pull request #16681
Opened 2022-03-25 17:38 UTC by FSAkeneo

Simplification/fix of useFetchProductQualityScore.

- [x] Tests

2022-03-25 17:39 UTC, FSAkeneo commented
/!\ until PLG-822 is merged into master, this PR includes its commits

2022-03-31 08:55 UTC, BryanS29-akeneo commented on src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/ProductEditForm/useFetchQualityScore.unit.ts
> +              console.log(result.current.outcome);
Did you forget this console.log ?

2022-03-31 09:21 UTC, BryanS29-akeneo approved these changes

2022-03-31 09:27 UTC, LaurentPetard approved these changes

2022-03-31 12:25 UTC, LaurentPetard requested changes
When a product has been updated from a bulk action, import, or API, we don't know how long the user will wait to see the new score. So in theses case we display the "In progress" badge.
The flashing "ghost" score should only be displayed when a product has been updated from the PEF (i.e. when the HTTP request to re-evaluate the product is in progress)

How can I change your own comment ??? (fsakeneo)

2022-04-01 15:46 UTC, FSAkeneo commented
> When a product has been updated from a bulk action, import, or API, we don't know how long the user will wait to see the new score. So in theses case we display the "In progress" badge. The flashing "ghost" score should only be displayed when a product has been updated from the PEF (i.e. when the HTTP request to re-evaluate the product is in progress)

I've made some changes, it should be fine now when we don't have the score and we did not save juste before (the "long pending after mass update" scenario).
I also noticed than when we switch from PEF to product grid while score retrievel retrying is in progress it wasn't (and could not have been) stopped. Fixed that I think.

2022-04-08 12:31 UTC, LaurentPetard approved these changes

2022-04-08 14:01 UTC, merged