RAB-169: Add ability to override separator regex in TagsInput
akeneo/pim-community-dev pull request #16991
Opened 2022-05-10 13:45 UTC by ValentinMumble

2022-05-10 13:48 UTC, pierrejolly commented on front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
> +     * Tags to display.
Are you sure ?

2022-05-10 14:01 UTC, ghoussard requested changes

2022-05-10 14:01 UTC, ghoussard commented on front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
> +     * Tags to display.
```suggestion
     * Tags to display
```

2022-05-11 07:20 UTC, StevenVAIDIE approved these changes

2022-05-11 17:49 UTC, merged