RAB-723: Create tag before submitting with non-empty input
akeneo/pim-community-dev pull request #17053
Opened 2022-05-17 15:18 UTC by ValentinMumble

- Create a tag when submitting (hitting Enter) with a non-empty input
- Add ellipsis when having a very long tag

Before: 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/3492179/168847081-dc5a732a-5f02-42c3-af0d-7c78621e763f.png">

After:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/3492179/168846934-8a86e09e-9af4-42d7-8fa5-49888e24a727.png">

2022-05-17 15:57 UTC, ghoussard requested changes

2022-05-17 15:57 UTC, ghoussard commented on front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
> +const TagText = styled.span`
Would you move styled components declarations before the function component please ? 😆

2022-05-18 07:50 UTC, ghoussard approved these changes

2022-05-18 12:43 UTC, StevenVAIDIE approved these changes

2022-05-18 12:43 UTC, StevenVAIDIE commented on front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
> +const TagText = styled.span`
UP

2022-05-18 12:44 UTC, merged