PIM-10466: Pull-up 6.0 => master
akeneo/pim-community-dev pull request #17107
Opened 2022-05-25 12:57 UTC by BryanS29-akeneo

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-05-30 06:52 UTC, olivierpontier approved these changes

2022-05-31 07:56 UTC, olivierpontier requested changes
The file src/Akeneo/Platform/CommunityVersion.php has been removed in master since the way to handle the version of the PIM has been refactored. We should ignore it from the pull up

2022-06-03 13:07 UTC, BryanS29-akeneo commented on upgrades/schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution.php
> +        $this->addSql('CREATE INDEX start_time_idx ON akeneo_batch_job_execution (start_time)');
The initial problem was differences between reference base and current base. This script makes sure that `start_time_idx` index exists and if not, it creates it. This index is normally already created in the base of our customers in 6.0 since there is [another script older than it](https://github.com/akeneo/pim-community-dev/blob/1fc4c92b5c414c7b26df2beca01045374350d1e9/upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php#L16) does. As seen with @ValentinMumble, raccoons made this condition in case there is a hole in the racket and [the update](https://github.com/akeneo/pim-enterprise-dev/blob/9d02bd1832d0b500ba2c038af46e660118de8458/src/Akeneo/Tool/Bundle/DatabaseMetadataBundle/Resources/reference.pimdbschema.txt#L214) made in `reference.pimdbschema.txt` takes the index into account. In this way, the risk of error is 100% covered.
So, normally the index is already created in 6.0 with [this migration script](https://github.com/akeneo/pim-community-dev/blob/1fc4c92b5c414c7b26df2beca01045374350d1e9/upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php#L16)  (2021-03-12).
In your opinion, does the script need to be refactor or add `ALGORITHM IN PLACE, LOCK NONE` will be enough ?

2022-06-03 13:48 UTC, nmarniesse approved these changes

2022-06-03 13:56 UTC, olivierpontier approved these changes

2022-06-06 08:07 UTC, merged