GRF-231  internal API endpoint to GET a category for edition purpose
akeneo/pim-community-dev pull request #17622
Opened 2022-08-09 13:40 UTC by FSAkeneo

**Description (for Contributor and Core Developer)**

New endpoint /category/rest/<id> to get information about categories.
contains
- core category data : id, parent_id, code,labels
- permissions settings
- attributes values

Values are hardcoded and return attribute values corresponding to the (yet to exist on backend) hardcoded template.

2022-08-16 08:55 UTC, BryanS29-akeneo commented
Why re-create models in `back\Api` directory ? Can't we use the ones that are in `back/Domain`?
Having same models is a bit confusing

2022-08-16 09:28 UTC, etiennekerbastard commented
> 

Yep if they're identical we can use the one in `back\Domain` imo

2022-08-17 08:34 UTC, antoinetrouve requested changes

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        $readModel = new CategoryReadModel(
Move Category model in controller for the serialization

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/CategoryReadModel.php
> +
add method fromDomain() => retrieve a data from database.

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        $readModel = new CategoryReadModel(
Rename class to category and move to Api/model/read

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        return $readModel;
return read model category build with Category model (check permission for edit page)

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        $permissions = new Permissions([
check ACL pimee_enrich_category_edit_permissions and feature flag permission. (if no right => ALL ou [] = no permission. To check)

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Domain/ValueObject/CategoryId.php
> +    public function __toString(): string
no need

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category.yml
> +    _controller: Akeneo\Category\back\Infrastructure\Controller\InternalAPI\GetCategoryController
check path internalApi directory and no back

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/tests/.php_cs.php
> +return (new PhpCsFixer\Config())
desactivate Yoda style

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/Category.php
> +    public function __construct(
private

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/Category.php
> +class Category
To delete, see ReadModel upgrade.

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/CategoryId.php
> +class CategoryId
Use primitif int instead

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/Code.php
> +class Code
use string instead

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/LabelCollection.php
> +final class LabelCollection
use array instead

2022-08-17 08:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/CategoryReadModel.php
> +        private Category $category,
Use only category model

2022-08-17 12:50 UTC, antoinetrouve commented on src/Akeneo/Category/back/tests/.php_cs.php
> +return (new PhpCsFixer\Config())
done

2022-08-17 12:50 UTC, antoinetrouve commented on src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category.yml
> +    _controller: Akeneo\Category\back\Infrastructure\Controller\InternalAPI\GetCategoryController
Done

2022-08-17 13:21 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +    public function __invoke(GetCategoryQuery $query): CategoryReadModel
done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        $readModel = new CategoryReadModel(
Done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/CategoryReadModel.php
> +
Done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/Category.php
> +class Category
Done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/Code.php
> +class Code
Done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/CategoryReadModel.php
> +        private Category $category,
Done

2022-08-17 16:10 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryHandler.php
> +        $readModel = new CategoryReadModel(
Done

2022-08-17 16:11 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/CategoryId.php
> +class CategoryId
Done

2022-08-17 16:11 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Model/Category/LabelCollection.php
> +final class LabelCollection
Done

2022-08-17 16:12 UTC, antoinetrouve approved these changes

2022-08-18 07:43 UTC, BryanS29-akeneo approved these changes

2022-08-18 12:24 UTC, amigaire commented on src/Akeneo/Category/back/Application/GetCategoryQueryHandler.php
> +        // TODO : check ACL and Feature flag (see PR review)
Has it been viewed?

2022-08-18 12:42 UTC, olivierpontier commented
Are the models `src/Akeneo/Category/back/Api/Model/Permissions.php` and `src/Akeneo/Category/back/Api/Model/AttributeValues.php` still useful? Did we agree on exposing only the `Model\Read\Category`?

2022-08-18 14:42 UTC, antoinetrouve commented
> Are the models `src/Akeneo/Category/back/Api/Model/Permissions.php` and `src/Akeneo/Category/back/Api/Model/AttributeValues.php` still useful? Did we agree on exposing only the `Model\Read\Category`?

Yes you are right. I just foget to delete it.

2022-08-18 14:43 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/GetCategoryQueryHandler.php
> +        // TODO : check ACL and Feature flag (see PR review)
Yes it still to do when we 'll work on the permission.

2022-08-18 15:52 UTC, etiennekerbastard approved these changes

2022-08-19 07:24 UTC, merged