GRF-220 : Upsert Category command handler
akeneo/pim-community-dev pull request #17631
Opened 2022-08-10 08:55 UTC by antoinetrouve

**Description (for Contributor and Core Developer)**

- Create the upsert command handler for the update.
- /!\ The Creation process still to do and the saver (see [GRF-221](https://github.com/akeneo/pim-community-dev/pull/17617)) need to be include when ready.

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-08-10 09:38 UTC, BryanS29-akeneo commented on src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
> +        $category = $this->findCategoryByCode->__invoke($command->categoryCode());
we don't have to call exactly `__invoke`,  you can replace it by `$category = ($this->findCategoryByCode)($command->categoryCode());`

2022-08-10 09:40 UTC, BryanS29-akeneo approved these changes

2022-08-10 11:43 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
> +        $category = $this->findCategoryByCode->__invoke($command->categoryCode());
done

2022-08-10 12:15 UTC, olivierpontier commented on src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
> +        $this->updater->update($category, $command->userIntents());
The naming is confusing, by reading the code I don't understand the difference between `updateCategory` and calling the updater. Is the second service more like a saver in charge of storing the updated category object in the database ?

2022-08-10 12:17 UTC, olivierpontier commented on src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidatorSpec.php
> +    function it_throw_an_exception_when_the_localize_intents_are_not_distinct(ExecutionContext $context, ConstraintViolationBuilderInterface $violationBuilder)
```suggestion
    function it_throws_an_exception_when_the_localize_intents_are_not_distinct(ExecutionContext $context, ConstraintViolationBuilderInterface $violationBuilder)
```

2022-08-10 12:24 UTC, olivierpontier commented on src/Akeneo/Category/back/Api/Command/UserIntents/LocalizeUserIntent.php
> +namespace Akeneo\Category\Api\Command\UserIntents;
Weird, it seems the DummyHandler class has been renamed into LocalizeUserIntent. It is due to a conflict resolution?

2022-08-10 12:29 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Command/UserIntents/LocalizeUserIntent.php
> +namespace Akeneo\Category\Api\Command\UserIntents;
No. The localizeUserIntent is an interface for the userIntent. Not directly related to the dummy handler.

2022-08-10 12:32 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
> +        $this->updater->update($category, $command->userIntents());
I just renaming to saver which is more corresponding to its usage.

2022-08-10 12:32 UTC, antoinetrouve commented on src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php
> +        $this->updater->update($category, $command->userIntents());
```suggestion
        $this->updateCategory($category, $command);

        $this->saver->update($category, $command->userIntents());
```

2022-08-10 12:34 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Command/UserIntents/LocalizeUserIntent.php
> +namespace Akeneo\Category\Api\Command\UserIntents;
This interface is used to identify the user intent localizable. For now, It's mainly used to validate the userIntents given in parameter in the command. see validator.yml confg

2022-08-10 12:35 UTC, antoinetrouve commented on src/Akeneo/Category/back/Api/Command/UserIntents/LocalizeUserIntent.php
> +namespace Akeneo\Category\Api\Command\UserIntents;
done

2022-08-10 12:36 UTC, antoinetrouve commented on src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidatorSpec.php
> +    function it_throw_an_exception_when_the_localize_intents_are_not_distinct(ExecutionContext $context, ConstraintViolationBuilderInterface $violationBuilder)
updated

2022-08-10 13:08 UTC, etiennekerbastard requested changes

2022-08-10 13:08 UTC, etiennekerbastard commented on src/Akeneo/Category/back/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidator.php
> +    public function validate($value, Constraint $constraint)
public function validate(**array** $value, Constraint $constraint): **void**

2022-08-10 13:08 UTC, etiennekerbastard commented on src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
> +    function it_creates_and_save_a_category(
function it_creates_and_save**s**_a_category(

2022-08-11 12:16 UTC, antoinetrouve commented on src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php
> +    function it_creates_and_save_a_category(
done :)

2022-08-11 12:17 UTC, antoinetrouve commented on src/Akeneo/Category/back/Infrastructure/Validation/LocalizeUserIntentsShouldBeUniqueValidator.php
> +    public function validate($value, Constraint $constraint)
I cannot change the function signature. I have to respect the original one. The declaration must be compatible with ConstraintValidatorInterface.

2022-08-11 12:32 UTC, etiennekerbastard approved these changes

2022-08-11 14:07 UTC, merged