GRF-233 : Add value collection in query sql to save a base category
akeneo/pim-community-dev pull request #17863
Opened 2022-09-06 14:35 UTC by antoinetrouve

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-09-06 15:28 UTC, BryanS29-akeneo approved these changes

2022-09-07 07:49 UTC, etiennekerbastard requested changes

2022-09-07 07:49 UTC, etiennekerbastard commented on src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
> +        $values = $categoryModel->getAttributes();
Here you have to respect the format of the JSON format laid out in the [ADR](https://www.notion.so/akeneo/Enrich-Categories-flexibility-and-maintenance-of-the-data-23b99c6ac4af4997b8c307f4e94291ca#bf6ab26e7d9d4f109c1b6f55fdbb27f9). You need to have a table of composite keys at the start of the JSON before the list of attributes concatenated with their locale codes

2022-09-07 07:49 UTC, etiennekerbastard commented on src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
> +        $values = $categoryModel->getAttributes();
same here

2022-09-07 09:21 UTC, antoinetrouve commented on src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
> +        $values = $categoryModel->getAttributes();
Yes this is the role of the handler to manage data format. As per discussion i add some test to validate the data and their values saved in db.

2022-09-07 09:21 UTC, antoinetrouve commented on src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php
> +        $values = $categoryModel->getAttributes();
same here ;)

2022-09-07 09:32 UTC, etiennekerbastard approved these changes

2022-09-20 06:57 UTC, merged