PH-273: Add a job to schedule periodic tasks
akeneo/pim-community-dev pull request #18214
Opened 2022-10-24 16:09 UTC by Airmanbzh

**Description (for Contributor and Core Developer)**

Add a job to schedule dqi periodic tasks that should not be executed live

2022-10-25 07:56 UTC, jmleroux requested changes

2022-10-25 07:56 UTC, jmleroux commented on src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
> +    schedule_periodic_tasks:
```suggestion
    schedule_dqi_periodic_tasks:
```

2022-10-25 07:56 UTC, jmleroux commented on src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
> +        alias:     schedule_periodic_tasks
```suggestion
        alias:     schedule_dqi_periodic_tasks
```

2022-10-25 07:56 UTC, jmleroux commented on src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
> +    schedule_periodic_tasks:
```suggestion
    schedule_dqi_periodic_tasks:
```

2022-10-25 07:56 UTC, jmleroux commented on src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
> +        alias:     schedule_periodic_tasks
```suggestion
        alias:     schedule_dqi_periodic_tasks
```

2022-10-25 07:56 UTC, jmleroux commented on upgrades/schema/Version_7_0_20221024171500_add_scheduled_jobs.php
> +            'schedule_periodic_tasks',
```suggestion
            'schedule_dqi_periodic_tasks',
```

2022-10-25 07:56 UTC, jmleroux commented on upgrades/test_schema/Version_7_0_20221024171500_add_scheduled_jobs_integration.php
> +    private const MIGRATION_LABEL = '_7_0_20221024171500_add_scheduled_jobs_integration';
```suggestion
    private const MIGRATION_LABEL = '_7_0_20221024171500_add_scheduled_jobs';
```

2022-10-25 07:56 UTC, jmleroux commented on src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
> +        class: Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Connector\Tasklet\SchedulePeriodicTasksTasklet
```suggestion
    Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Connector\Tasklet\SchedulePeriodicTasksTasklet:
```

We now try to not use aliases when possible

2022-10-25 19:27 UTC, jmleroux approved these changes

2022-10-27 05:59 UTC, niarcotyk approved these changes

2022-10-27 09:18 UTC, merged