GRF-540: Disable Enrich Category feature for the 7.0 release
akeneo/pim-community-dev pull request #18614
Opened 2022-12-07 15:20 UTC by etiennekerbastard

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-12-07 16:09 UTC, BryanS29-akeneo requested changes

2022-12-07 16:09 UTC, BryanS29-akeneo commented on config/packages/akeneo_feature_flag.yml
> +        - { feature: 'enriched_category', service: 'akeneo.feature_flag.service.only_saas_feature'}
replace by the existing service `only_serenity_feature`

2022-12-07 16:09 UTC, BryanS29-akeneo commented on .env
> -FLAG_ENRICHED_CATEGORY_ENABLED=0
do not remove this line

2022-12-07 16:09 UTC, BryanS29-akeneo commented on src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
> -parameters:
do not remove this declaration of service

2022-12-07 16:09 UTC, BryanS29-akeneo commented on src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasFeatureFlag.php
> +class OnlySaasFeatureFlag implements FeatureFlag
not necessary to declare an other feature flag service, `OnlySerenityFeatureFlag` already exists

2022-12-07 16:09 UTC, BryanS29-akeneo commented on src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
> +    akeneo.feature_flag.service.only_saas_feature:
not necessary

2022-12-12 07:49 UTC, antoinetrouve approved these changes

2022-12-12 07:53 UTC, amigaire approved these changes

2022-12-12 13:46 UTC, BryanS29-akeneo approved these changes

2022-12-12 15:19 UTC, merged