PIM-10687: Fix high memory consumption when computing completeness for prices with inactive currencies
akeneo/pim-community-dev pull request #18738
Opened 2022-12-20 09:09 UTC by mmetayer

Replaces #18737 

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2022-12-20 09:14 UTC, pierallard approved these changes
Quel talent

2022-12-20 09:15 UTC, Balamung approved these changes

2022-12-20 09:18 UTC, ahocquard requested changes
The fix is not correct. 

It should stop to generate all possible combinations.

2022-12-20 09:18 UTC, ahocquard commented on src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php
> +            $this->findActivatedCurrencies->forAllChannels() :
It does not solve the issue of memory consumption. It generates far too much combination if 20 currencies are active.

2022-12-20 17:05 UTC, ahocquard approved these changes

2022-12-21 09:45 UTC, Balamung approved these changes

2022-12-22 17:58 UTC, merged