PIM-10960: Fix no violation raised when importing variant with already existing siblings
akeneo/pim-community-dev pull request #19657
Opened 2023-04-25 13:57 UTC by MadeWilson

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2023-04-26 12:34 UTC, pierallard requested changes

2023-04-26 12:34 UTC, pierallard commented on tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
> -      "message": "Cannot set value \"[optionB]\" for the attribute axis \"a_simple_select\" on product model \"sub_product_model\", as the product model \"tshirt_sub_product_model\" already has this
This is not good IMHO. The user really want to set "optionB" and not "optionb".

2023-04-26 13:09 UTC, mmetayer commented on tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
> -      "message": "Cannot set value \"[optionB]\" for the attribute axis \"a_simple_select\" on product model \"sub_product_model\", as the product model \"tshirt_sub_product_model\" already has this
might be easier to update the `Akeneo\Pim\Enrichment\Component\Product\Validator\UniqueAxesCombinationSet ` class instead

2023-04-26 13:35 UTC, MadeWilson commented on tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
> -      "message": "Cannot set value \"[optionB]\" for the attribute axis \"a_simple_select\" on product model \"sub_product_model\", as the product model \"tshirt_sub_product_model\" already has this
I can format the value during the comparaison so I don't lose the original for the log. Fixed that.

2023-04-27 07:31 UTC, StevenVAIDIE commented on tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
> +    function it_raises_a_violation_if_there_is_a_duplicate_value_with_a_different_case_in_any_sibling_product_model(
Are we sure that we test the SDS problem ? Because this test already pass without the Validator changes

2023-04-28 09:03 UTC, MadeWilson commented on tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
> +    function it_raises_a_violation_if_there_is_a_duplicate_value_with_a_different_case_in_any_sibling_product_model(
fixed that test it should broke on current master

2023-04-28 15:23 UTC, StevenVAIDIE approved these changes

2023-05-03 13:33 UTC, ghoussard approved these changes

2023-05-12 11:16 UTC, closed without merging