PIM-10949: Remove duplicated variant product
akeneo/pim-community-dev pull request #19654
Opened 2023-04-25 09:56 UTC by Beninho

**Description (for Contributor and Core Developer)**

In order to fix data if exists duplicated variant product

**Definition Of Done (for Core Developer only)**

- [X] Tests
- [X] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

2023-04-25 10:01 UTC, cemorin commented on upgrades/schema/Version_8_0_20230425090000_remove_duplicated_variant_product.php
> +SELECT   COUNT(*) AS nbr_doublon, product_model_id, raw_values
```suggestion
SELECT   COUNT(*) AS nbr_duplicate, product_model_id, raw_values
```
It's chipotage

2023-04-25 10:02 UTC, cemorin approved these changes

2023-04-28 08:53 UTC, mmetayer requested changes
the pb is too complex to be executed in a doctrine migration, let's try to find another way to fix it

2023-04-28 08:53 UTC, mmetayer commented on upgrades/schema/Version_8_0_20230425090000_remove_duplicated_variant_product.php
> +SQL);
there's no index on raw_values, this query will take too long to execute, plus duplicate variant products doesn't necessarily means that the raw_values are exactly the same

2023-05-02 09:55 UTC, closed without merging